version: '3.3'
services:
  zachltech_web_landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site-zachltech-landing
    restart: unless-stopped
    ports:
      - 9800:3000